require: '@babel/register'
require:
  - esm
  - dotenv/config
recursive: true
reporter: mochawesome
reporter-options:
  reportDir: reports
  reportFilename: UsersAPI
  overwrite: true
  html: true
  json: false